#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json

# Dictionnaire complet de traduction des noms de pays en français
translations = {
    "Aden": "Aden",
    "Afghanistan": "Afghanistan",
    "Albania": "Albanie",
    "Algeria": "Algérie",
    "Andorra": "Andorre",
    "Anglo-Egyptian Sudan": "Soudan anglo-égyptien",
    "Angola": "Angola",
    "Anguilla": "Anguilla",
    "Antarctica": "Antarctique",
    "Antigua and Barbuda": "Antigua-et-Barbuda",
    "Argentina": "Argentine",
    "Aruba": "Aruba",
    "Australia": "Australie",
    "Azores": "Açores",
    "Bahamas": "Bahamas",
    "Barbados": "Barbade",
    "Basutoland": "Basutoland",
    "Bechuanaland": "Bechuanaland",
    "Belgian Congo": "Congo belge",
    "Belgium": "Belgique",
    "Bermuda": "Bermudes",
    "Bhutan": "Bhoutan",
    "Bolivia": "Bolivie",
    "Bonaire": "Bonaire",
    "Bouvet Island": "Île Bouvet",
    "Brazil": "Brésil",
    "British Guiana": "Guyane britannique",
    "British Honduras": "Honduras britannique",
    "British Indian Ocean Territory": "Territoire britannique de l'océan Indien",
    "British Malaya": "Malaisie britannique",
    "British Somaliland": "Somaliland britannique",
    "British Virgin Islands": "Îles Vierges britanniques",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgarie",
    "Burma": "Birmanie",
    "Cabo Verde": "Cabo Verde",
    "Cameroons": "Cameroun",
    "Canada": "Canada",
    "Canarias": "Canaries",
    "Caroline Island": "Îles Carolines",
    "Cayman Islands": "Îles Caïmans",
    "Ceylon": "Ceylan",
    "Chile": "Chili",
    "China": "Chine",
    "Chosen Korea": "Corée Chosen",
    "Christmas Island": "Île Christmas",
    "Cocos Islands": "Îles Cocos",
    "Colombia": "Colombie",
    "Comoros": "Comores",
    "Cook Islands": "Îles Cook",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba",
    "Curacao": "Curaçao",
    "Cyprus": "Chypre",
    "Czechoslovakia": "Tchécoslovaquie",
    "Denmark": "Danemark",
    "Dominica": "Dominique",
    "Dominican Republic": "République dominicaine",
    "Ecuador": "Équateur",
    "Egypt": "Égypte",
    "El Salvador": "El Salvador",
    "Ellice Islands": "Îles Ellice",
    "Estonia": "Estonie",
    "Falkland Islands": "Îles Malouines",
    "Faroe Islands": "Îles Féroé",
    "Fiji": "Fidji",
    "Finland": "Finlande",
    "France": "France",
    "French Equatorial Africa": "Afrique équatoriale française",
    "French Guiana": "Guyane française",
    "French Indochina": "Indochine française",
    "French Polynesia": "Polynésie française",
    "French Somaliland": "Somaliland français",
    "French Southern Territories": "Terres australes françaises",
    "French West Africa": "Afrique-Occidentale française",
    "Gambia": "Gambie",
    "Germany": "Allemagne",
    "Gibraltar": "Gibraltar",
    "Glorioso Islands": "Îles Glorieuses",
    "Gold Coast": "Côte-de-l'Or",
    "Greece": "Grèce",
    "Greenland": "Groenland",
    "Grenada": "Grenade",
    "Guadeloupe": "Guadeloupe",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guernsey": "Guernesey",
    "Haiti": "Haïti",
    "Heard Island and McDonald Islands": "Îles Heard et McDonald",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungary": "Hongrie",
    "Iceland": "Islande",
    "India": "Inde",
    "Iran": "Iran",
    "Iraq": "Irak",
    "Ireland": "Irlande",
    "Isle of Man": "Île de Man",
    "Italian East Africa": "Afrique-Orientale italienne",
    "Italy": "Italie",
    "Jamaica": "Jamaïque",
    "Jan Mayen": "Jan Mayen",
    "Japan": "Japon",
    "Jersey": "Jersey",
    "Juan De Nova Island": "Île Juan de Nova",
    "Kenya": "Kenya",
    "Kiribati": "Kiribati",
    "Kuwait": "Koweït",
    "Latvia": "Lettonie",
    "Lebanon": "Liban",
    "Liberia": "Libéria",
    "Libya": "Libye",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituanie",
    "Luxembourg": "Luxembourg",
    "Macau": "Macao",
    "Madagascar": "Madagascar",
    "Madeira": "Madère",
    "Maldives": "Maldives",
    "Malta": "Malte",
    "Manchukuo": "Mandchoukouo",
    "Marianas Islands": "Îles Mariannes",
    "Marshall Islands": "Îles Marshall",
    "Martinique": "Martinique",
    "Mauritius": "Île Maurice",
    "Mayotte": "Mayotte",
    "Mexico": "Mexique",
    "Monaco": "Monaco",
    "Mongolia": "Mongolie",
    "Montserrat": "Montserrat",
    "Morocco": "Maroc",
    "Mozambique": "Mozambique",
    "Nauru": "Nauru",
    "Nepal": "Népal",
    "Netherlands": "Pays-Bas",
    "Netherlands Guiana": "Guyane néerlandaise",
    "Netherlands Indies": "Indes néerlandaises",
    "New Caledonia": "Nouvelle-Calédonie",
    "New Hebrides": "Nouvelles-Hébrides",
    "New Zealand": "Nouvelle-Zélande",
    "Nicaragua": "Nicaragua",
    "Nigeria": "Nigéria",
    "Niue": "Niue",
    "Norfolk Island": "Île Norfolk",
    "Northern Rhodesia": "Rhodésie du Nord",
    "Norway": "Norvège",
    "Nyasaland": "Nyassaland",
    "Oman": "Oman",
    "Palau": "Palaos",
    "Palestine": "Palestine",
    "Panama": "Panama",
    "Paraguay": "Paraguay",
    "Peru": "Pérou",
    "Philippines": "Philippines",
    "Pitcairn": "Île Pitcairn",
    "Poland": "Pologne",
    "Portugal": "Portugal",
    "Portuguese Guinea": "Guinée portugaise",
    "Portuguese Timor": "Timor portugais",
    "Puerto Rico": "Porto Rico",
    "Qatar": "Qatar",
    "Rio De Oro": "Rio de Oro",
    "Romania": "Roumanie",
    "Réunion": "Réunion",
    "Saba": "Saba",
    "Saint Barthelemy": "Saint-Barthélemy",
    "Saint Eustatius": "Saint-Eustache",
    "Saint Helena": "Sainte-Hélène",
    "Saint Kitts and Nevis": "Saint-Kitts-et-Nevis",
    "Saint Lucia": "Sainte-Lucie",
    "Saint Martin": "Saint-Martin",
    "Saint Pierre and Miquelon": "Saint-Pierre-et-Miquelon",
    "Saint Vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
    "Samoa Island": "Île Samoa",
    "San Marino": "Saint-Marin",
    "Sao Tome and Principe": "São Tomé-et-Principe",
    "Saudi Arabia": "Arabie saoudite",
    "Seychelles": "Seychelles",
    "Siam": "Siam",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singapour",
    "Sint Maarten": "Sint Maarten",
    "Solomon Islands": "Îles Salomon",
    "South Georgia and South Sandwich Islands": "Géorgie du Sud et Îles Sandwich du Sud",
    "Southern Rhodesia": "Rhodésie du Sud",
    "Southwest Africa": "Afrique du Sud-Ouest",
    "Spain": "Espagne",
    "Spanish Guinea": "Guinée espagnole",
    "Spanish Morocco": "Maroc espagnol",
    "Svalbard": "Svalbard",
    "Swaziland": "Eswatini",
    "Sweden": "Suède",
    "Switzerland": "Suisse",
    "Syria": "Syrie",
    "Taiwan": "Taïwan",
    "Tanganyika": "Tanganyika",
    "Tannu Tuva": "Tannu Tuva",
    "Territory Of Alaska": "Territoire de l'Alaska",
    "Territory of Hawaii": "Territoire de Hawaï",
    "Territory of New Guinea": "Territoire de la Nouvelle-Guinée",
    "Territory of Papua": "Territoire de Papouasie",
    "Tibet": "Tibet",
    "Tokelau": "Tokelau",
    "Tonga": "Tonga",
    "Transjordan": "Transjordanie",
    "Trinidad and Tobago": "Trinité-et-Tobago",
    "Tunisia": "Tunisie",
    "Turkey": "Turquie",
    "Turks and Caicos Islands": "Îles Turques-et-Caïques",
    "US Virgin Islands": "Îles Vierges des États-Unis",
    "Uganda": "Ouganda",
    "Union Of South Africa": "Union d'Afrique du Sud",
    "Union of Soviet Socialist Republics": "Union des républiques socialistes soviétiques",
    "United Kingdom": "Royaume-Uni",
    "United States": "États-Unis",
    "United States Minor Outlying Islands": "Îles Mineures des États-Unis",
    "Uruguay": "Uruguay",
    "Vatican City": "Cité du Vatican",
    "Venezuela": "Venezuela",
    "Wallis and Futuna": "Wallis-et-Futuna",
    "Yemen": "Yémen",
    "Yugoslavia": "Yougoslavie"
}

# Lire le fichier GeoJSON
with open('public/world 1939 4326.geojson', 'r', encoding='utf-8') as f:
    geojson_data = json.load(f)

# Ajouter la traduction à chaque feature
for feature in geojson_data['features']:
    if 'NAME' in feature['properties']:
        country_name = feature['properties']['NAME']
        feature['properties']['NAME_FR'] = translations.get(country_name, country_name)

# Sauvegarder le fichier modifié
with open('public/world 1939 4326.geojson', 'w', encoding='utf-8') as f:
    json.dump(geojson_data, f, ensure_ascii=False, indent=2)

print("✓ Traductions complétées avec succès!")
print(f"✓ {len(geojson_data['features'])} pays traités")
